title: BM Base
syntax: XML
supportedLanguages: []
properties:
  - name: New
    type: Flag
    icon: arrow-up
    style: green
  - name: В разработке
    type: Flag
    style: orange-red
    icon: accessibility
versions:
  - "0.1"
